#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

cp 0/alpha.water.orig 0/alpha.water
cp 0/tau0.orig 0/tau0

runApplication blockMesh
python3 createTopoSet.py
runApplication topoSet
runApplication subsetMesh cylinderCells -overwrite -patch walls
runApplication setFields
runApplication $application

#------------------------------------------------------------------------------
