#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication blockMesh
runApplication topoSet
runApplication subsetMesh boxCells -overwrite -patch walls
cp 0/alpha.water.orig 0/alpha.water
cp 0/tau0.orig 0/tau0
runApplication setFields
runApplication $application

#------------------------------------------------------------------------------
